apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-service-account
  namespace: default  # You can change this to another namespace if needed


# kubectl apply -f service-account.yaml
# kubectl create serviceaccount my-service-account
