apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: db-snapshot
spec:
  volumeSnapshotClassName: csi-aws-snapshot
  source:
    persistentVolumeClaimName: db-pvc


# 1. Volume Snapshots
# Take snapshots of existing volumes for backup or disaster recovery.
# SnapshotClass, VolumeSnapshot, and VolumeSnapshotContent objects are used.
# Example Use-case: Rollback to a known good state of a DB.