# Volume Expansion
# Resize existing volumes when more space is needed.
# Requires StorageClass with allowVolumeExpansion: true.


apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: expandable-storage
provisioner: ebs.csi.aws.com
allowVolumeExpansion: true


---
# You can then edit PVC to request more storage:

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: expandable-pvc
spec:
  resources:
    requests:
      storage: 20Gi  # Resize to 20Gi
