apiVersion: v1
kind: Pod
metadata:
  name: my-configpod
  namespace: ramtest
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    env:
    - name: "APP_COLOR"
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: APP_COLOR
    
    volumeMounts:
      - name: config-volume
        mountPath: "/etc/config"

    volumes:
    - name: config-volume
      configMap:
        name: my-config

