apiVersion: v1
kind: Secret
metadata:
  name: my-app-secret
type: Opaque
data:
  username: YWRtaW4=   # 'admin' base64 encoded
  password: MWYyZDFlMmU2N2Rm  # '1f2d1e2e67df' base64 encoded

# ⚙️ Note: Always base64 encode secret values when creating via YAML.