apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
- resources:
  - secrets
  providers:
  - kms:
      name: my-kms-provider
      endpoint: unix:///tmp/kms-socket.sock
  - aesgcm:
      keys:
      - name: key1
        secret: <base64-encoded-secret-key>
  - identity: {}


# Enable it via API server flag:
# --encryption-provider-config=/etc/kubernetes/encryption-config.yaml

# ✅ This ensures secrets are encrypted in etcd rather than stored as plaintext.