apiVersion: v1
kind: Pod
metadata:
  name: pod-with-init-containers
spec:
  initContainers:
    - name: wait-for-db
      image: busybox
      command: ['sh', '-c', 'until nc -z my-database 3306; do echo waiting for db; sleep 2; done;']
  containers:
    - name: app
      image: my-app
