apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1  # Start with 1 replica
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          requests:
            cpu: 100m  # Request 100m CPU
            memory: 128Mi
          limits:
            cpu: 500m  # Limit to 500m CPU
            memory: 512Mi

# kubectl apply -f nginx-deployment.yaml

---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
