apiVersion: v1
kind: Pod
metadata:
  name: secure-pod
  labels:
    app: secure-app
  annotations:
    container.apparmor.security.beta.kubernetes.io/secure-container: "runtime/default"
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 2000
    seccompProfile:
      type: RuntimeDefault
  volumes:
    - name: aws-secrets
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "aws-secrets"
  containers:
    - name: secure-container
      image: secure-app:latest
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
        runAsNonRoot: true
      resources:
        limits:
          cpu: "500m"
          memory: "512Mi"
        requests:
          cpu: "250m"
          memory: "256Mi"
      volumeMounts:
        - name: aws-secrets
          mountPath: "/mnt/secrets-store"
          readOnly: true
      env:
        - name: AWS_SECRET
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: secret-key
  nodeSelector:
    kubernetes.io/os: linux
  tolerations:
    - key: "node-role.kubernetes.io/master"
      effect: "NoSchedule"
  restartPolicy: Always
