apiVersion: v1
kind: Pod
metadata:
  name: multi-container-with-volume
spec:
  containers:
    - name: app-container
      image: app-image
      volumeMounts:
        - name: shared-volume
          mountPath: /data
    - name: sidecar-container
      image: sidecar-image
      volumeMounts:
        - name: shared-volume
          mountPath: /data
  volumes:
    - name: shared-volume
      emptyDir: {}  # A temporary volume for the Pod
