apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler
  namespace: kube-system
spec:
  containers:
  - name: kube-scheduler
    image: k8s.gcr.io/kube-scheduler:v1.21.0
    command:
      - kube-scheduler
      - --kubeconfig=/etc/kubernetes/scheduler.conf
      - --leader-elect=true
