apiVersion: batch/v1
kind: CronJob
metadata:
  name: demojob
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 2 #keep 3 successful jobs
  failedJobsHistoryLimit: 1 #keep 1 failed job
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: nginx
            image: nginx
            command: ["sh", "-c", "sleep 20; exit 0"]
          restartPolicy: Never
