apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  containers:
  - name: my-app
    image: my-app-image

# As environment variables:
    env:
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: my-app-secret
          key: username
    - name: DB_PASS
      valueFrom:
        secretKeyRef:
          name: my-app-secret
          key: password

# As mounted files:

    volumeMounts:
    - name: secret-volume
      mountPath: "/etc/secret"
      readOnly: true

    # volumes:
    # - name: secret-volume
    #   secret:
    #     secretName: my-app-secret

