apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-service-account-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: my-service-account  # Name of the Service Account
  namespace: default
- kind: User
  name: alice        # User to bind
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader  # The Role being bound
  apiGroup: rbac.authorization.k8s.io


# kubectl apply -f role.yaml
# kubectl apply -f rolebinding.yaml
