apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-app-pvc
  namespace: production
spec:
  accessModes:
    - ReadWriteOnce # Single node access, can be changed to RWO/ROX/RWX depending on need
  storageClassName: gp2-sc
  resources:
    requests:
      storage: 20Gi # Size of volume

# Notes:
# Adjust accessModes based on application requirement:
# ReadWriteOnce (RWO): Mounted as read-write by a single node.
# ReadOnlyMany (ROX): Mounted as read-only by many nodes.
# ReadWriteMany (RWX): Mounted as read-write by many nodes (e.g., NFS, EFS).
# Make sure namespace is aligned with application deployment.