# ✅ Example: Full Pod SecurityContext Example for Minimal Privileges

apiVersion: v1
kind: Pod
metadata:
  name: secure-pod
spec:
  securityContext:
    runAsNonRoot: true
    fsGroup: 2000
  containers:
  - name: app
    image: my-app-image
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      runAsUser: 1000
    volumeMounts:
    - mountPath: "/app/config"
      name: config-volume
  volumes:
  - name: config-volume
    configMap:
      name: app-config
  automountServiceAccountToken: false
