apiVersion: v1
kind: Pod
metadata:
  name: etcd
  namespace: kube-system
spec:
  containers:
  - name: etcd
    image: quay.io/coreos/etcd:v3.4.9
    command:
      - etcd
      - --data-dir=/var/lib/etcd
      - --listen-client-urls=https://localhost:2379
      - --advertise-client-urls=https://localhost:2379
