apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: default # Your prefered namespace
spec:
  provider: aws
  secretObjects:
  - secretName: k8s-secret
    type: Opaque
    data:
      username: bXl1c2Vy  # "myuser" base64   echo -n "myuser" | base64
      password: bXlwYXNz  # "mypass" base64   echo -n "mypass" | base64
  parameters:     
    objects: | 
      - objectName: MySecret 
        objectType: secretsmanager
        jmesPath:
          - path: username
            objectAlias: db_username 
          - path: password 
            objectAlias: db_password


# ✅ Explanation:
# Field	Purpose
# objectName	Name of the secret in AWS
# objectType	secretsmanager (fixed for AWS Secrets)
# jmesPath.path	The specific key you want to extract
# jmesPath.objectAlias	Filename under the mounted volume