apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-app-statefulset
spec:
  serviceName: "my-app"          # Headless Service for stable network identity
  replicas: 3                    # Number of replicas (Pods)
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: my-app:v1
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: my-app-storage
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: my-app-storage        # Name of the PVC template
      spec:
        accessModes: [ReadWriteOnce] # PVC will request a PersistentVolume
        resources:
          requests:
            storage: 1Gi            # Storage request per Pod
