apiVersion: v1
kind: Service
metadata:
  name: my-stateful-service
spec:
  clusterIP: None
  selector:
    app: my-app
  ports:
    - port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-statefulset
spec:
  serviceName: "my-stateful-service"  # Refers to the headless service
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: app-container
          image: my-app-image
          ports:
            - containerPort: 8080
