apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: Nodeport
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
  selector:
    app: myapp


# kubectl create 0f service-defination.yaml
# kubectl get svs
# minikube service myapp-service --url
